# This playbook installs apps and packages needed for general development
- hosts: localhost
  tasks:
    - name: Install Alacritty config file
      copy:
        src: ~/.dotfiles/windows/alacritty/alacritty.yml
        dest: /mnt/c/Users/jemillar/AppData/Roaming/alacritty/alacritty.yml
