# This playbook installs apps and packages needed for general development
- hosts: localhost
  tasks:
    - name: Copy WSL SSH key
      copy:
        src: '{{ item }}'
        dest: /mnt/c/Users/jemillar/.ssh
      with_fileglob:
        - ~/.ssh/id_rsa*
