# This playbook configures the attached disk that's used for Docker
- hosts: localhost
  tasks:
  - name: Mount disk for Docker usage
    mount:
      path: /mnt/docker
      src: UUID=8594c301-8d3c-4d4e-b328-450d4bcb8e24
      state: present
