apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotfiles
  namespace: default
  labels:
    app: dotfiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotfiles
  template:
    metadata:
      labels:
        app: dotfiles
    spec:
      containers:
      - name: dotfiles
        image: jessemillar/dotfiles:latest
        stdin: true
        tty: true
