apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotfiles
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dotfiles
        image: jessemillar/dotfiles:latest
