# This playbook installs apps and packages needed for work
- hosts: localhost
  tasks:
    - name: Install Helm
      homebrew:
        name: helm
        state: present
    - name: Install k3d
      homebrew:
        name: k3d
        state: present
    - name: Install packages to allow apt to use a repository over HTTPS
      become: yes
      shell: apt update && apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      register: result
      changed_when: result.stdout is not search("0 newly installed")
    - name: Add Docker's GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      become: yes
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      changed_when: false
    - name: Install Docker
      become: yes
      shell: apt install -y docker-ce docker-ce-cli containerd.io
      register: result
      changed_when: result.stdout is not search("0 newly installed")
