# This playbook installs things specific to my personal machines (e.g. some applications are disallowed on corporate-managed laptops)
- hosts: localhost
  roles:
    - geerlingguy.homebrew
  vars:
    homebrew_taps:
      - homebrew/cask
    homebrew_cask_apps:
      - dropbox