# This playbook installs apps and packages needed for working with Kubernetes
- hosts: localhost
  pre_tasks:
    - name: Make .bin directory
      file:
        path: ~/.bin
        state: directory
  tasks:
    - name: Install packages to allow apt to use a repository over HTTPS
      become: yes
      shell: apt update && apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      register: result
      changed_when: result.stdout is not search("0 newly installed")
    - name: Add Docker's GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      become: yes
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      changed_when: false
    - name: Install Docker
      become: yes
      shell: apt install -y docker-ce docker-ce-cli containerd.io
      register: result
      changed_when: result.stdout is not search("0 newly installed")
    - name: Create a Docker user group
      become: yes
      group:
        name: docker
        state: present
    - name: Add {{ ansible_user_id }} to the docker group
      become: yes
      user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes
    - name: Start the docker service
      become: yes
      service:
        name: docker
        state: started
    - name: Install cfssl
      homebrew:
        name: cfssl
        state: present
    - name: Install k3d
      homebrew:
        name: k3d
        state: present
    - name: Install kubectl
      homebrew:
        name: kubectl
        state: present
    - name: Install snap
      become: yes
      shell: apt install -y snap
      register: result
      changed_when: result.stdout is not search("0 newly installed")
    - name: Install microk8s via snap
      become: yes
      snap:
        name: microk8s
        state: present
        classic: yes
    - name: Start microk8s services
      become: yes
      shell: microk8s.enable dns dashboard registry
      changed_when: false
    - name: Install kustomize
      homebrew:
        name: kustomize
        state: present
    - name: Install Kubebuilder
      homebrew:
        name: kubebuilder
        state: present
    - name: Install fluxctl
      homebrew:
        name: fluxctl
        state: present
    - name: Install kind
      homebrew:
        name: kind
        state: present
    - name: Install the k wrapper
      shell: curl -L https://raw.githubusercontent.com/jakepearson/k/master/k -o ~/.bin/k && chmod +x ~/.bin/k
    - name: Install the h wrapper
      shell: curl -L https://raw.githubusercontent.com/jakepearson/h/master/h -o ~/.bin/h && chmod +x ~/.bin/h
