# This playbook installs things specific to my personal machines (e.g. some applications are disallowed on corporate-managed laptops)
- hosts: localhost
  roles:
    - geerlingguy.homebrew
  vars:
    homebrew_upgrade_all_packages: yes
    homebrew_taps:
      - homebrew/cask
    homebrew_cask_apps:
      - dropbox
    tasks:
      - name: Symlinking ~/Desktop to Dropbox
        command: ln -s ~/Desktop ~/Dropbox
      - name: Symlinking ~/Downloads to Dropbox
        command: ln -s ~/Downloads ~/Dropbox
