# This playbook installs apps and packages needed for general development
- hosts: localhost
  pre_tasks:
    - name: Stow dotfiles for ack
      command: stow ack
      changed_when: false
    - name: Stow dotfiles for Git
      command: stow git
      changed_when: false
    - name: Stow dotfiles for Neovim
      command: stow neovim
      changed_when: false
  tasks:
    - name: Tap antibody repository
      homebrew_tap:
        name: getantibody/tap
        state: present
    - name: Install ack
      homebrew:
        name: ack
        state: present
    - name: Install antibody
      homebrew:
        name: antibody
        state: present
    - name: Install bat
      homebrew:
        name: bat
        state: present
    - name: Install coreutils
      homebrew:
        name: coreutils
        state: present
    - name: Install fd
      homebrew:
        name: fd
        state: present
    - name: Install fdupes
      homebrew:
        name: fdupes
        state: present
    - name: Install ffmpeg
      homebrew:
        name: ffmpeg
        state: present
    - name: Install git
      homebrew:
        name: git
        state: present
    - name: Install go
      homebrew:
        name: go
        state: present
    - name: Install grep
      homebrew:
        name: grep
        state: present
    - name: Install gron
      homebrew:
        name: gron
        state: present
    - name: Install hub
      homebrew:
        name: hub
        state: present
    - name: Install imagemagick
      homebrew:
        name: imagemagick
        state: present
    - name: Install jq
      homebrew:
        name: jq
        state: present
    - name: Install neovim
      homebrew:
        name: neovim
        state: present
    - name: Install nmap
      homebrew:
        name: nmap
        state: present
    - name: Install nnn
      homebrew:
        name: nnn
        state: present
    - name: Install pipes-sh
      homebrew:
        name: pipes-sh
        state: present
    - name: Install python
      homebrew:
        name: python
        state: present
    - name: Install python3
      homebrew:
        name: python3
        state: present
    - name: Install shellcheck
      homebrew:
        name: shellcheck
        state: present
    - name: Install thefuck
      homebrew:
        name: thefuck
        state: present
    - name: Install tidy-html5
      homebrew:
        name: tidy-html5
        state: present
    - name: Install tldr
      homebrew:
        name: tldr
        state: present
    - name: Install tokei
      homebrew:
        name: tokei
        state: present
    - name: Install tree
      homebrew:
        name: tree
        state: present
    - name: Install uncrustify
      homebrew:
        name: uncrustify
        state: present
    - name: Install watch
      homebrew:
        name: watch
        state: present
    - name: Install zsh
      homebrew:
        name: zsh
        state: present
    - name: Install neovim Python module
      shell: pip3 install neovim
      register: result
      changed_when: "result.stdout is not search('Requirement already satisfied: neovim')"
    - name: Install nvim plugins
      command: nvim --headless +GoUpdateBinaries +PlugUpdate +PlugUpgrade +UpdateRemotePlugins +qall
      changed_when: false
    - name: Install vim-plug
      command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      changed_when: false
    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      register: result
      changed_when: result.stdout is not search("You already have Oh My Zsh installed.")
      failed_when: result.rc != 0 and result.stdout is not search("You already have Oh My Zsh installed.")
    - name: Stow dotfiles for Oh My Zsh
      command: stow zsh
      changed_when: false
