# Any dependencies needed for other playbooks to run successfully should be managed here
- hosts: localhost
  roles:
    - geerlingguy.homebrew
  vars:
    homebrew_upgrade_all_packages: yes
    homebrew_installed_packages:
      - stow
