# This playbook installs apps and packages needed for playing videogames
- hosts: localhost
  roles:
    - geerlingguy.homebrew
  vars:
    homebrew_upgrade_all_packages: yes
    homebrew_taps:
      - homebrew/cask
    homebrew_cask_apps:
      - epic-games
