# This playbook installs programs that are specific to my current employment
- hosts: localhost
  pre_tasks:
    - name: Stow dotfiles for IntelliJ IDEA
      command: stow intellij-idea
  roles:
    - geerlingguy.homebrew
  vars:
    homebrew_taps:
      - homebrew/cask
    homebrew_installed_packages:
      - maven
      - tomcat@8
    homebrew_cask_apps:
      - dbeaver-community
      - intellij-idea
      - java8
      - kafka-tool
      - slack
      - zoomus
      - zoomus-outlook-plugin
    homebrew_cask_uninstalled_apps:
      - android-platform-tools
      - sequel-pro
      - visualvm