# This playbook installs apps and packages needed for general development
- hosts: localhost
  pre_tasks:
    - name: Stow dotfiles for ack
      command: stow ack
    - name: Stow dotfiles for Git
      command: stow git
  roles:
    - geerlingguy.homebrew
  vars:
    homebrew_taps:
      - getantibody/tap
      - homebrew/cask
    homebrew_installed_packages:
      - ack
      - antibody
      - bat
      - coreutils
      - fd
      - fdupes
      - ffmpeg
      - git
      - go
      - grep
      - gron
      - hub
      - imagemagick
      - imagesnap
      - jq
      - neovim
      - nmap
      - nnn
      - pipes-sh
      - python3
      - shellcheck
      - thefuck
      - tidy-html5
      - tldr
      - tokei
      - trash
      - tree
      - uncrustify
      - wallpaper
      - watch
      - wifi-password
      - zsh
    homebrew_uninstalled_packages:
      - excel-compare
      - gist
      - mono
      - shpotify
    homebrew_cask_apps:
      - colorpicker-skalacolor
      - couleurs
      - docker
      - goland
      - kitematic
      - postman
      - qlmarkdown
      - qlstephen
    homebrew_cask_uninstalled_apps:
      - clion
      - dotnet
  tasks:
    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    - name: Use nvm to install Node.js
      command: nvm install node && nvm alias default node
    - name: Install Node.js packages
      command: npm install -g js-beautify prettydiff typescript typescript-formatter
    - name: Install nvim Python support
      command: pip3 install --user neovim
    - name: Install nvim plugins
      command: nvim --headless +PlugInstall +GoInstallBinaries +q
    - name: Install Oh My Zsh
      command: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    - name: Install vim-plug
      command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim