# This playbook represents apps and window/keyboard managers needed to get my system to a minimally "usable" state for my preferences
- hosts: localhost
  pre_tasks:
    - name: Stow dotfiles for Hammerspoon
      command: stow hammerspoon
    - name: Stow dotfiles for Karabiner-Elements
      command: stow karabiner-elements
    - name: Stow dotfiles for Kitty
      command: stow kitty
    - name: Stow dotfiles for skhd
      command: stow skhd
    - name: Stow dotfiles for Visual Studio Code
      command: stow visual-studio-code
    - name: Stow dotfiles for yabai
      command: stow yabai
  roles:
    - geerlingguy.homebrew
  vars:
    # Spotify doesn't have wonderful update support in Homebrew so this flag needs to be set to prevent failing the playbook if Spotify is already installed
    homebrew_cask_accept_external_apps: true
    homebrew_taps:
      - homebrew/cask
      - homebrew/cask-versions
      - koekeishiya/formulae
    homebrew_installed_packages:
      - skhd
      - stow
      - yabai
    homebrew_cask_apps:
      - 1password
      - alfred3
      - appcleaner
      - cyberduck
      - firefox
      - google-chrome
      - hammerspoon
      - karabiner-elements
      - keepingyouawake
      - kitty
      - rocket
      - spotify
      - the-unarchiver
      - visual-studio-code
      - vlc
      - whichspace
    homebrew_cask_uninstalled_apps:
      - bitbar
  tasks:
    - name: Starting service for skhd
      command: brew services start skhd
    - name: Starting service for yabai
      command: brew services start yabai
  post_tasks:
    - name: Remove dotfiles via Stow for BitBar
      command: stow -D bitbar
