# This playbook represents apps and window/keyboard managers needed to get my system to a minimally "usable" state for my preferences
- hosts: localhost
  pre_tasks:
    - name: Stow dotfiles for Hammerspoon
      command: stow hammerspoon
      changed_when: false
    - name: Stow dotfiles for Karabiner-Elements
      command: stow karabiner-elements
      changed_when: false
    - name: Stow dotfiles for Kitty
      command: stow kitty
      changed_when: false
    - name: Stow dotfiles for skhd
      command: stow skhd
      changed_when: false
      changed_when: false
    - name: Stow dotfiles for yabai
      command: stow yabai
      changed_when: false
  tasks:
    homebrew_tap:
      name: homebrew/cask-fonts,homebrew/cask-versions,koekeishiya/formulae
      state: present
    homebrew:
      name: skhd,stow,yabai
      state: present
    homebrew_cask:
      name:
       1password,alfred3,appcleaner,cyberduck,firefox,font-fontawesome,google-chrome,hammerspoon,karabiner-elements,keepingyouawake,kitty,rocket,spotify,the-unarchiver,vlc
      state: present
    - name: Starting service for skhd
      command: brew services start skhd
      register: result
      changed_when: result.stdout is not search("already started")
    - name: Starting service for yabai
      command: brew services start yabai
      register: result
      changed_when: result.stdout is not search("already started")
