# This playbook installs apps and packages needed for general development
- hosts: localhost
  tasks:
    homebrew_cask:
      name: colorpicker-skalacolor,couleurs,docker,goland,kitematic,postman,qlmarkdown,qlstephen
      state: present
