#!/bin/sh

GAP_SIZE=20

pkill -x sxhkd
sxhkd &

dropbox-cli start

$HOME/.dotfiles/scripts/keyboard

pkill -x panel
$HOME/.dotfiles/scripts/panel &

feh --bg-fill ~/Dropbox/Wallpaper/Desktop/cups.jpg

bspc monitor DP-1 -n L -d 1 2 3 4 5
bspc monitor DVI-I-1 -n R -d 6 7 8 9 10

bspc config border_width 1
bspc config window_gap $GAP_SIZE

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
