sudo: false
os:
- linux
language: node_js

node_js:
- 6.3.1

script:
- npm install -g gulp
- gulp

after_success:
- npm run package

env:
  global:
    secure: QAM0xjbrfX2M2hEFpUR95vJM5o9Q9CkrkYPa2zNbKqRIqXFQ+++LHBTEj3uVCnewqN92Od4lyaYlmUOuSQhAPenp6FbU7sIwU556mDYHfkJeFYw6QqheiKPpe89Zdt6/TgB/v/Muzchl+ts2NI/JE1Lh7jgTn7jlQaGWkj/e5MVUQmYACu57Vd7BXA9m8PqZPhUQuHL0DnjeT/QeI4hS0o1H5Q1/14VRCJ120679v+EAACrwxVQ1ZUtMhja7r0q1CzotLtrzSRbgJ5laMiOkXtmYMqawiVwr1d098vUxgS3d27geH/oa1W/tDNKRDNzae0/4aQxokdM0ZXIJC/Ts2nGaD6Z6iqWDq2l279d/kkAOKZ4u829G4oO22V1bOxbFpqN08a3yFqpGSZvsP/Jukn1mUj325q+haC7CWqc29ycsgqB54FHVmS6mGB3rbUSXdH5eCzPylG/XXYuNCIQOGcDmH3K4CsXK9mhrBJV/wZhKPKn8HYtWC8a+2eN9B7wxxz3CRDPi7vmRtYF75x0mD7GBQhw1fwBXZVfIhhH1DJGZfl5pz10Iza+Mfgc3ga0CQjO+705DHZjIRD3RZb+9/dOcrXaOVMHUb4SFj3/ElbEpLzqRy0LuaEX5kCAOSQouNb2N5drW47U36C4gLgZnA8hwL0AcctoEg3d5oKA3mFQ=

deploy:
- provider: releases
  api_key:
    secure: rgl8x1sjWLXO/hueU8pL0aBSg0PT+PJiNDRxn+EMuzSESEDgihMBCyz8CR+gjSqfYDXnnPLqUk/BZL+3H1cAWiRVPlh7A5icYd1x7g6xuswQxvVamdBQ8e3BSsdj3BFWu4YYKzSW3ZoCpg5ANL1e5EUysPkmorrsNma8jt3O0TLDU7eSkxtRm4/UOunWVytckH15nmOjo5AWeiuJ3qc+iuSFFjg4/Mm9OfRfHI47Fc9m7hx5g/9nGvV+o5vJNq1i+Gii3+0rd1ewGyD0kkVl7JetYOAiUN8Q6qA58TVXOlFZ45lxGAwzOSryDmpOw8tjn/aVGugibmqbd1yVKimQnXW8bAQrGcJ3obYsbImAPTrhJRLrn3LRQichj9sbvBhH4b4F9K40be+sTOh2oNUyqfgN+qoKWz9tDk2S3g5moEnCUp4jED61hEWEoUNX7mV+hPQpnJHvSkbXPlXrIfslEWYytNYQL1TBJXOg99fKLjIHqOYokt0nOw46uaGN2IxStFMDTpSCF3+h47uYRBItrk9tHxT/ZmfL1tUD2n4W5dLvqLkp7YLIbuSdhgFD9+GVaB8vrQnkxw5pbXzmP7FHs4INE6qvOlwrDh5WwZDSCB8zSRtuTfiKoJXBhAjIv0p8HbZKhOxgdbGoCj0IO1XgTJys0lcPhyf55mEEblb0N/I=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: trixnz/vscode-lua
    tags: true
- provider: script
  script: npm run travis-deploy
  skip_cleanup: true
  on:
    repo: trixnz/vscode-lua
    tags: true
