#! /bin/sh

sxhkd &

compton -b

dropbox-cli start

feh --bg-fill ~/Dropbox/Wallpaper/Desktop/cups.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
