#! /bin/sh

GAP_SIZE=5
SCREEN_WIDTH=1440
BAR_HEIGHT=25

sxhkd &

compton -b

dropbox-cli start

$HOME/.dotfiles/linux/keyboard.sh

setxkbmap -option caps:escape

killall -9 lemonbar
$HOME/.dotfiles/linux/personal/lemonbar.sh | lemonbar -p -f "Roboto Mono:size=8" -g $[$SCREEN_WIDTH-$GAP_SIZE*2]x$BAR_HEIGHT+$GAP_SIZE+$GAP_SIZE

xbacklight -set 41

feh --bg-fill ~/Dropbox/Wallpaper/Desktop/foggy-trees.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap $GAP_SIZE

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
