#! /bin/sh

sxhkd &

compton -b

dropbox-cli start

$HOME/.dotfiles/linux/keyboard.sh

setxkbmap -option caps:escape

xbacklight -set 41

feh --bg-fill ~/Dropbox/Wallpaper/Desktop/foggy-trees.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
