#! /bin/sh

GAP_SIZE=20
SCREEN_WIDTH=2560
BAR_HEIGHT=20

pkill -x sxhkd
sxhkd &

dropbox-cli start

$HOME/.dotfiles/scripts/keyboard

pkill -x panel
$HOME/.dotfiles/work/panel &

feh --bg-fill ~/Dropbox/Wallpaper/Desktop/cups.jpg

bspc monitor DP-1 -n 0 -d I II III IV V
bspc monitor DVI-I-1 -n 1 -d VI VII VIII IX X

bspc config border_width 1
bspc config window_gap $GAP_SIZE

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
