#!/bin/bash

# Get panel variables
# Must be an absolute path so systemd can use this script
. /home/jessemillar/.dotfiles/scripts/panel_config

BATTERY_STATE=$(cat /sys/class/power_supply/BAT0/status)
ACTUAL_CHARGE=$(cat /sys/class/power_supply/BAT0/charge_now)
MAX_CHARGE=$(cat /sys/class/power_supply/BAT0/charge_full)
CHARGE=$(echo "$ACTUAL_CHARGE/$MAX_CHARGE*100" | bc -l)
CHARGE_PERCENT=${CHARGE%.*}

if [ "$CHARGE_PERCENT" -gt "100" ]; then
	CHARGE_PERCENT="100"
fi


if [ $BATTERY_STATE = "Charging" ]; then
	ICON="\uE3E7"
else
	ICON="\uE1A4"
fi

echo -e "C$ICON $CHARGE_PERCENT%" > $PANEL_FIFO
