#!/bin/sh

# Import configuration values
. $HOME/.dotfiles/scripts/panel_config

# Detect the number of monitors
MONITOR_COUNT=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			clock="%{F$COLOR_DEFAULT} ${line#?} %{B-}%{F-}"
			;;
		V*)
			# volume output
			volume="%{F$COLOR_DEFAULT} ${line#?} %{B-}%{F-}"
			;;
		B*)
			# brightness output
			brightness="%{F$COLOR_DEFAULT} ${line#?} %{B-}%{F-}"
			;;
		C*)
			# charge output
			charge="%{F$COLOR_DEFAULT} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			wml=""
			wmr=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $MONITOR_COUNT -lt 2 ] && shift && continue
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE
								CHAR=$CHAR_FREE
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE
								CHAR=$CHAR_FOCUSED_FREE
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED
								CHAR=$CHAR_OCCUPIED
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED
								CHAR=$CHAR_FOCUSED_OCCUPIED
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT
								CHAR=$CHAR_URGENT
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT
								CHAR=$CHAR_FOCUSED_URGENT
								;;
						esac

						if [ $MONITOR_COUNT -eq 2 ]; then
							if [ $name -lt 6 ]; then
								wml="${wml}%{F${FG}}%{A:bspc desktop -f ${name}:}  ${CHAR}  %{A}%{F-}"
							else
								wmr="${wmr}%{F${FG}}%{A:bspc desktop -f ${name}:}  ${CHAR}  %{A}%{F-}"
							fi
						else
							wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:}  ${CHAR}  %{A}%{F-}"
						fi
						;;
				esac
				shift
			done
			;;
	esac

	if [ $MONITOR_COUNT -eq 2 ]; then
		printf "%s\n" "%{Sf}%{c}${wml}%{Sl}%{c}${wmr}%{r}${volume}${clock}"
	else
		printf "%s\n" "%{l}${wm}%{r}${volume}${brightness}${charge}${clock}"
	fi
done
