#!/bin/sh

# Import configuration values
. $HOME/.dotfiles/scripts/panel_config

# Detect the number of monitors
MONITOR_COUNT=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			clock="%{F$COLOR_SYS_FG} ${line#?} %{B-}%{F-}"
			;;
		V*)
			# volume output
			volume="%{F$COLOR_FOCUSED_FREE_FG} ${line#?} %{B-}%{F-}"
			;;
		B*)
			# brightness output
			brightness="%{F$COLOR_FOCUSED_FREE_FG} ${line#?} %{B-}%{F-}"
			;;
		C*)
			# charge output
			charge="%{F$COLOR_FOCUSED_FREE_FG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $MONITOR_COUNT -lt 2 ] && shift && continue
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								CHAR=$'\uE313'
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								CHAR=$'\uE25D'
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								CHAR=$'\uE316'
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								CHAR=$'\uE318'
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								CHAR=$'\uE313'
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								CHAR=$'\uE318'
								;;
						esac
						wm="${wm}%{F${FG}}%{A:bspc desktop -f ${name}:}  ${CHAR}  %{A}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac

	if [ $MONITOR_COUNT -eq 2 ]; then
		printf "%s\n" "%{Sf}%{c}${wm}%{Sl}%{r}${volume}${clock}"
	else
		printf "%s\n" "%{l}${wm}%{r}${volume}${brightness}${charge}${clock}"
	fi
done
