#!/bin/sh

. $HOME/.dotfiles/scripts/panel_config

export PATH=$PATH:"`dirname $0`"
. $HOME/.dotfiles/scripts/panel_config

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config bottom_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
clock -sf 'S%b %d %l:%M %p' > "$PANEL_FIFO" &
$HOME/.dotfiles/scripts/volume &

$HOME/.dotfiles/scripts/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -b -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -o $PANEL_FONT_OFFSET -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done

[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
