#!/bin/bash

# Get panel variables
. $HOME/.dotfiles/scripts/panel_config

MUTE_STATUS=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $6}'`
VOLUME_PERCENT=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $4}'`

if [ $MUTE_STATUS = "off" ]; then
	echo -e "V\uE04f" > $PANEL_FIFO
else
	if [ $VOLUME_PERCENT -gt 66 ]; then
		ICON="\uE050"
	elif [ $VOLUME_PERCENT -gt 33 ]; then
		ICON="\uE04D"
	else
		ICON="\uE04E"
	fi

	echo -e "V$ICON $VOLUME_PERCENT%" > $PANEL_FIFO
fi
