#!/bin/bash

# Get panel variables
. $HOME/.dotfiles/scripts/panel_config

MUTE_STATUS=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $6}'`
VOLUME_PERCENT=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $4}'`

if [ $MUTE_STATUS = "on" ]; then
	echo -e "V\uE04f" > $PANEL_FIFO
else
	echo -e "V\uE050 $VOLUME_PERCENT" > $PANEL_FIFO
fi
