name: Publish Docker image

on: [push]

jobs:

  publish-docker-image:
    runs-on: ubuntu-latest
    steps:

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Bootstrap reverb
        run: ./bootstrap-reverb.sh

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jessemillar/dotfiles:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
