name: Build Status

on: [push]

jobs:

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        check_together: 'yes'
        additional_files: '.zshenv .functionsrc .aliasrc .asciirc'

  publish-docker-image:
    runs-on: ubuntu-latest
    steps:

      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bootstrap reverb
        run: ./bootstrap-reverb.sh

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jessemillar/dotfiles
          tags: latest
          cache_froms: jessemillar/dotfiles:latest
